pipeline:
  name: Rmo3
  identifier: Rmo3
  projectIdentifier: shashank
  orgIdentifier: shashank
  tags: {}
  stages:
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Shashank"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
